resources:
  repositories:
    - repository: devopsTemplates
      type: github
      endpoint: DfE Signin
      name: DFE-Digital/operations-devops-pipeline-templates

trigger:
  branches:
    include:
    - master
    exclude:
    - develop/*


variables:
  applicationName: ncsauth

stages:
- stage: Build
  jobs:
  - template: /Application/dotnet/jobs/build-application.yml@devopsTemplates
    parameters:
      applicationName: $(applicationName)
      webPublish: false

- stage: Deploy
  jobs:
  - template: /Application/dotnet/jobs/deploy-function.yml@devopsTemplates
    parameters:
      applicationName: $(applicationName)
      environmentName: dev
      serviceConnection: $(serviceConnection)
      subscriptionId: $(subscriptionId)
      resourceGroupName: $(resourceGroupName)
      location: $(deploymentLocation)
      templatePath: '$(Build.SourcesDirectory)/arm/template.json'
      overrideParameters: '-applicationName "ncsauth"
        -environmentName "dev"
        -publisherEmail "test@test.com"
        -publisherName "deploymentTest"
        -apimSku "Developer"
        -apimSkuCount "1"
        -servicePlanSkuName "B1"
        -servicePlanSkuTier "Basic"
        -servicePlanSkuCount "1"
        -secondaryStorageLocation "northeurope"
        -alertWebHookUrl "http://www.test.com"
        -B2CTenant "B2Cdemotenant"
        -B2CSignUpPolicy "B2C_1A_signup_invitation"
        -B2CSignupConfirmPolicy "B2C_1A_signup_confirmation"
        -B2CPasswordResetConfirmPolicy "B2C_1A_passwordResetConformation"
        -B2CClientId "8cbcfb4f-f998-45eb-9d18-737dc6f5f5e6"
        -B2CRedirectUri "https://jwt.ms"
        -B2CAuthorizationUrl "https://{0}.b2clogin.com/{0}.onmicrosoft.com/{1}/oauth2/v2.0/authorize?client_id={2}&nonce={4}&redirect_uri={3}&scope=openid&response_type=id_token"
        -ClientSigningKey ""
        -SMTPServer "smtp.sendgrid.net"
        -SMTPPort "587"
        -SMTPUseSSL true
        -SMTPFromAddress "aman.gupta@digital.education.gov.uk"
        -SMTPSubject "Sign-in to NCS"
        -SignupEmailSubject "Create your account"
        -SignupConfirmationEmailSubject "Verify your account"
        -PasswordResetConfirmationEmailSubject "Verify your account"
        -AccountActivationEmailExpiryInSeconds "86400"
        -ncs-dss-search-api-url "https://at.api.nationalcareersservice.org.uk/search/api/"
        -ncs-dss-search-api-version "v2"'
  - task: EapimManageProductRelease@1
    inputs:
      azureSubscription: 'S141D.bsvc.cip.azdo'
      AddOrRemoveProduct: 'Add'
      ProductName: 'NCS Identity'
      RequiresSubscription: true
      RequiresApproval: true
      isPublished: false
      APICapability: 'Customer Engagement'
      APIEnvironment: 'Development'