resources:
  repositories:
    - repository: devopsTemplates
      type: github
      endpoint: DfE Signin
      name: DFE-Digital/operations-devops-pipeline-templates

trigger:
  branches:
    include:
    - master
    - feature/*
    exclude:
    - develop/*


variables:
  armOutputsName: b2cOutputs
  applicationName: ncsauth

stages:
- stage: build
  jobs:
  - template: /Application/dotnet/jobs/build-application.yml@templates
    parameters:
      applicationName: $(applicationName)
      webPublish: false

- stage: armDeployDev
  displayName: Deployment
  jobs:
  - deployment: deployDev
    displayName: Dev deployment
    environment: dev
    strategy:
      runOnce:
        deploy:
          steps:
          - template: .vsts-deploy.yml
            parameters:
              serviceConnection: $(serviceConnection)
              subscriptionId: $(subscriptionId)
              resourceGroupName: $(resourceGroupName)
              applicationName: $(applicationName)
              environmentName: dev
              location: $(deploymentLocation)
              overrideParameters: '-applicationName "ncsauth"
                -environmentName "dev"
                -publisherEmail "test@test.com"
                -publisherName "deploymentTest"
                -apimSku "Developer"
                -apimSkuCount "1"
                -servicePlanSkuName "B1"
                -servicePlanSkuTier "Basic"
                -servicePlanSkuCount "1"
                -secondaryStorageLocation "northeurope"
                -alertWebHookUrl "http://www.test.com"
                -B2CTenant ""
                -B2CSignUpPolicy ""
                -B2CSignupConfirmPolicy ""
                -B2CPasswordResetConfirmPolicy ""
                -B2CClientId ""
                -B2CRedirectUri ""
                -B2CAuthorizationUrl ""
                -ClientSigningKey ""
                -SMTPServer ""
                -SMTPUsername ""
                -SMTPPassword ""
                -SMTPUseSSL true
                -SMTPFromAddress ""
                -SMTPSubject ""
                -SignupEmailSubject ""
                -SignupConfirmationEmailSubject ""
                -PasswordResetConfirmationEmailSubject ""'