name: $(BuildDefinitionName)_tag-$(BuildID)_at-$(Date:yyyyMMdd)$(Rev:.r)
resources:
  repositories:
    - repository: self
      persistCredentials: true
      clean: true
    - repository: devopsTemplates
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/operations-devops-pipeline-templates

pr:
  branches:
    include:
    - develop
    - master

variables:
- name: applicationName
  value: authncs
- name: parsedTestExtensionAppId
  value: $[ replace(variables['testProxyIdentityAppClientId'],'-','') ]
- name: parsedDevExtensionAppId
  value: $[ replace(variables['devProxyIdentityAppClientId'],'-','') ]
- group: ncs-b2c-global

stages:

- stage: devTenantMockSetup
  displayName: Tenant Mock Setup - DEV
  dependsOn:
  - build
  jobs:
  - template: yaml/jobs/tenant-mocked-setup-grouped.yml
    parameters:
      environmentName: dev
      variableGroupName: ncs-b2c-dev
      applicationName: $(applicationName)
      signinRedirectRoot: s141d01-signin-int.azurewebsites.net
      eapimRootUrl: dev-api-customerengagement.platform.education.gov.uk

  - job: devEapimOperationSetup
    displayName: EAPIM Operation Setup
    pool:
      vmImage: windows-latest
    steps:
    - template: yaml/steps/enable-mock-policies.yml
      parameters:
        eapimServiceConnection: $(eapimServiceConnection)
        eapimResourceGroupName: c106d01-eapim-custeng
        eapimServiceName: c106d01-apim-custeng

- stage: build
  displayName: Build and Test
  jobs:
  - template: /Application/dotnet/jobs/build-application.yml@devopsTemplates
    parameters:
      applicationName: $(applicationName)
      webPublish: false
      nugetConfigPath: nuget.config
      testProjectPath: '$(Build.SourcesDirectory)\tests\MockPolicyTests\MockPolicyTests.csproj'

  - template: yaml/jobs/tenant-setup-grouped.yml
    parameters:
      environmentName: dev
      variableGroupName: ncs-b2c-dev
      applicationName: $(applicationName)
      signinRedirectRoot: s141d01-signin-int.azurewebsites.net
      eapimRootUrl: dev-api-customerengagement.platform.education.gov.uk

  - job: devEapimOperationSetup
    displayName: EAPIM Operation Setup
    pool:
      vmImage: windows-latest
    steps:
    - template: yaml/steps/clear-mock-policies.yml
      parameters:
        eapimServiceConnection: $(eapimServiceConnection)
        eapimResourceGroupName: c106d01-eapim-custeng
        eapimServiceName: c106d01-apim-custeng
