name: $(BuildDefinitionName)_tag-$(BuildID)_at-$(Date:yyyyMMdd)$(Rev:.r)
resources:
  repositories:
    - repository: self
      persistCredentials: true
      clean: true
    - repository: devopsTemplates
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/operations-devops-pipeline-templates

trigger:
  branches:
    include:
    - master
    exclude:
    - develop/*

variables:
  applicationName: ncsauth
  eapimProductName: 'NCS Identity'

stages:
- stage: Build
  jobs:
  - template: /Application/dotnet/jobs/build-application.yml@devopsTemplates
    parameters:
      applicationName: $(applicationName)
      webPublish: false

- stage: deployDev
  displayName: Deploy - DEV
  jobs:
  - template: yaml/jobs/deploy.yml
    parameters:
      environmentName: 'dev'
      environmentId: 'd01'
      serviceConnection: $(devServiceConnection)
      subscriptionId: $(devSubscriptionId)
      deploymentPrimaryLocation: $(deploymentPrimaryLocation)
      deploymentSecondaryLocation: $(deploymentSecondaryLocation)
      deployApim: true

- stage: deployTest
  displayName: Deploy - TEST
  jobs:
  - template: yaml/jobs/deploy.yml
    parameters:
      environmentName: 'test'
      environmentId: 't01'
      serviceConnection: $(testServiceConnection)
      subscriptionId: $(testSubscriptionId)
      deploymentPrimaryLocation: $(deploymentPrimaryLocation)
      deploymentSecondaryLocation: $(deploymentSecondaryLocation)
      deployApim: false
