name: $(BuildDefinitionName)_tag-$(BuildID)_at-$(Date:yyyyMMdd)$(Rev:.r)
resources:
  repositories:
    - repository: self
      persistCredentials: true
      clean: true
    - repository: devopsTemplates
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/operations-devops-pipeline-templates

trigger:
  branches:
    include:
    - master
    exclude:
    - develop/*

variables:
  applicationName: ncsauth
  environmentName: dev
  eapimProductName: 'NCS Identity'
  b2cAuthUrl: "https://{0}.b2clogin.com/{0}.onmicrosoft.com/{1}/oauth2/v2.0/authorize?client_id={2}&nonce={4}&redirect_uri={3}&scope=openid&response_type=id_token"
  armVariables: [
  -applicationName "$(applicationName)",
  -publisherEmail "test@test.com",
  -publisherName "deploymentTest",
  -servicePlanSkuName "B1",
  -servicePlanSkuTier "Basic",
  -servicePlanSkuCount "1",
  -secondaryStorageLocation "$(deploymentSecondaryLocation)",
  -alertWebHookUrl "http://www.test.com",
  -B2CTenant "B2Cdemotenant",
  -B2CSignUpPolicy "B2C_1A_signup_invitation",
  -B2CSignupConfirmPolicy "B2C_1A_signup_confirmation",
  -B2CPasswordResetConfirmPolicy "B2C_1A_passwordResetConformation",
  -B2CClientId "$(b2cClientId)",
  -B2CRedirectUri "https://jwt.ms",
  -B2CAuthorizationUrl "$(b2cAuthUrl)",
  -ClientSigningKey "$(clientSigningKey)",
  -SMTPServer "$(smtpServer)",
  -SMTPUsername "$(smtpUsername)",
  -SMTPPassword "$(smtpPassword)",
  -SMTPFromAddress "$(smtpFromAddress)",
  -SMTPSubject "Sign-in to NCS",
  -SignupEmailSubject "Create your account",
  -SignupConfirmationEmailSubject "Verify your account",
  -PasswordResetConfirmationEmailSubject "Verify your account",
  -AccountActivationEmailExpiryInSeconds "86400",
  -NCSApimSubscriptionKey "$(ncsApimSubscriptionKey)",
  -NCSDSSApiKey "$(ncsDssApiKey)",
  -NCSDSSSearchApiUrl "$(ncsDssSearchApiUrl)",
  -NCSDSSSearchApiVersion "$(ncsDssSearchApiVersion)"
  ]


stages:
- stage: Build
  jobs:
  - template: /Application/dotnet/jobs/build-application.yml@devopsTemplates
    parameters:
      applicationName: $(applicationName)
      webPublish: false

- stage: deployDev
  displayName: Deployment - DEV
  jobs:
  - template: /Application/dotnet/jobs/deploy-function.yml@devopsTemplates
    parameters:
      applicationName: $(applicationName)
      environmentName: 'dev'
      serviceConnection: $(devServiceConnection)
      subscriptionId: $(devSubscriptionId)
      resourceGroupName: $(projectId)d01-$(applicationName)
      location: $(deploymentPrimaryLocation)
      templatePath: '$(Build.SourcesDirectory)/arm/template.json'
      overrideParameters: ${{ join(variables.armVariables, ' ') }} -environmentName "dev"
      eapimRegister: true
      eapimServiceConnection: $(eapimServiceConnection)
      eapimProductName: 'NCS Identity'
      eapimProductContactEmail: paul.sheridan@digital.education.gov.uk
      eapimApiPublishedName: 'NCS Identity'
      eapimApiOpenApiSchemaPath: '/api/swagger'
      eapimApiPublishedPath: ncsauth
      eapimApiXmlPolicyPath: '$(Build.SourcesDirectory)/eapim/api/policy.xml'

- stage: deployTest
  displayName: Deployment - TEST
  jobs:
  - template: /Application/dotnet/jobs/deploy-function.yml@devopsTemplates
    parameters:
      applicationName: $(applicationName)
      environmentName: 'test'
      serviceConnection: $(testServiceConnection)
      subscriptionId: $(testSubscriptionId)
      resourceGroupName: $(projectId)t01-$(applicationName)
      location: $(deploymentPrimaryLocation)
      templatePath: '$(Build.SourcesDirectory)/arm/template.json'
      overrideParameters: ${{ join(variables.armVariables, ' ') }} -environmentName "test"