resources:
  repositories:
    - repository: devopsTemplates
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/operations-devops-pipeline-templates

trigger:
  branches:
    include:
    - mastersigni
    exclude:
    - develop/*


variables:
  applicationName: ncsauth
  environmentName: dev
  eapimProductName: 'NCS Identity'

stages:
- stage: Build
  jobs:
  - template: /Application/dotnet/jobs/build-application.yml@devopsTemplates
    parameters:
      applicationName: $(applicationName)
      webPublish: false

- stage: Deploy
  jobs:
  - template: /Application/dotnet/jobs/deploy-function.yml@devopsTemplates
    parameters:
      applicationName: $(applicationName)
      environmentName: $(environmentName)
      serviceConnection: $(serviceConnection)
      subscriptionId: $(devSubscriptionId)
      resourceGroupName: $(projectId)d01-$(applicationName)
      location: $(deploymentPrimaryLocation)
      templatePath: '$(Build.SourcesDirectory)/arm/template.json'
      overrideParameters: '-applicationName "$(applicationName)"
        -environmentName "dev"
        -publisherEmail "test@test.com"
        -publisherName "deploymentTest"
        -apimSku "Developer"
        -apimSkuCount "1"
        -servicePlanSkuName "B1"
        -servicePlanSkuTier "Basic"
        -servicePlanSkuCount "1"
        -secondaryStorageLocation "$(deploymentSecondaryLocation)"
        -alertWebHookUrl "http://www.test.com"
        -B2CTenant ""
        -B2CSignUpPolicy ""
        -B2CSignupConfirmPolicy ""
        -B2CPasswordResetConfirmPolicy ""
        -B2CClientId ""
        -B2CRedirectUri ""
        -B2CAuthorizationUrl ""
        -ClientSigningKey ""
        -SMTPServer ""
        -SMTPUsername ""
        -SMTPPassword ""
        -SMTPUseSSL true
        -SMTPFromAddress ""
        -SMTPSubject ""
        -SignupEmailSubject ""
        -SignupConfirmationEmailSubject ""
        -PasswordResetConfirmationEmailSubject ""'
      eapimRegister: true
      eapimServiceConnection: $(eapimServiceConnection)
      eapimProductName: 'NCS Identity'
      eapimProductContactEmail: paul.sheridan@digital.education.gov.uk
      eapimApiPublishedName: 'NCS Identity'
      eapimApiOpenApiSchemaPath: '$(Build.SourcesDirectory)/eapim/api/schema.json'
      eapimApiPublishedPath: ncsauth
      eapimApiXmlPolicyPath: '$(Build.SourcesDirectory)/eapim/api/policy.xml'