resources:
  repositories:
    - repository: devopsTemplates
      type: github
      endpoint: DfE Digital
      name: DFE-Digital/operations-devops-pipeline-templates

trigger:
  branches:
    include:
    - master
    - feature/*
    exclude:
    - develop/*

variables:
  armOutputsName: b2cOutputs
  applicationName: ncsauth

stages:
- stage: buildAndDeploy
  jobs:
  - deployment: deployDev
    environment: dev
    strategy:
      runOnce:
        deploy:
          steps:
          - template: .vsts-deploy.yml
            parameters:
              serviceConnection: $(serviceConnection)
              applicationName: $(applicationName)
              environmentName: dev
              location: $(deploymentLocation)
              overrideParameters: '-applicationName "ncsauth"
                -environmentName "dev"
                -publisherEmail "test@test.com"
                -publisherName "deploymentTest"
                -apimSku "Developer"
                -apimSkuCount "1"
                -servicePlanSkuName "B1"
                -servicePlanSkuTier "Basic"
                -servicePlanSkuCount "1"
                -secondaryStorageLocation "northeurope"
                -alertWebHookUrl "http://www.test.com"'