trigger:
  branches:
    include:
    - master
    exclude:
    - develop/*

stages:
- stage: buildAndDeploy
  jobs:
  - job: armDeploy
    steps:
      - checkout: self
      - download: none
      - task: AzureResourceManagerTemplateDeployment@3
        displayName: Create Infrastructure
        inputs:
          deploymentScope: 'Resource Group'
          azureResourceManagerConnection: $(serviceConnection)
          subscriptionId: $(subscriptionId)
          resourceGroupName: $(resourceGroupName)
          location: $(deploymentLocation)
          csmFile: '$(Build.SourcesDirectory)/arm/template.json'
          overrideParameters: |
            -applicationName ncsauth
            -environmentName dev
            -publisherEmail test@test.com
            -publisherName deploymentTest
            -apimSku Developer
            -apimSkuCount 1
            -servicePlanSkuName F1
            -servicePlanSkuTier Free
            -servicePlanSkuCount 0
            -secondaryStorageLocation northeurope
            -actionGroupRecieverEmailAddress test@test.com      
            -alertWebHookUrl http://www.test.com
          deploymentMode: 'Incremental'              
      
