name: $(BuildDefinitionName)_tag-$(BuildID)_at-$(Date:yyyyMMdd)$(Rev:.r)
resources:
  repositories:
    - repository: self
      persistCredentials: true
      clean: true
    - repository: devopsTemplates
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/operations-devops-pipeline-templates

trigger:
  branches:
    include:
    - master
    exclude:
    - develop/*

variables:
- name: applicationName
  value: ncsauth
- group: ncs-b2c-global

stages:

- stage: build
  displayName: Build
  jobs:
  - template: /Application/dotnet/jobs/build-application.yml@devopsTemplates
    parameters:
      applicationName: $(applicationName)
      webPublish: false

- stage: deployDev
  displayName: Deploy - DEV
  jobs:
  - template: yaml/jobs/deploy.yml
    parameters:
      environmentName: 'test'
      environmentId: 't01'
      serviceConnection: $(devServiceConnection)
      subscriptionId: $(devSubscriptionId)
      clientId: $(devAzureB2cTenantId)
      graphAccessClientId: $(devGraphAccessClientId)
      graphAccessClientSecret: $(devGraphAccessClientSecret)
      deploymentPrimaryLocation: $(deploymentPrimaryLocation)
      deploymentSecondaryLocation: $(deploymentSecondaryLocation)
      deployApim: true
      eapimEnvironmentName: 'Test'

- stage: deployTest
  dependsOn:
  - deployDev
  displayName: Deploy - TEST
  jobs:
  - template: yaml/jobs/deploy.yml
    parameters:
      environmentName: 'test'
      environmentId: 't01'
      serviceConnection: $(testServiceConnection)
      subscriptionId: $(testSubscriptionId)
      clientId: $(testAzureB2cTenantId)
      graphAccessClientId: $(testGraphAccessClientId)
      graphAccessClientSecret: $(testGraphAccessClientSecret)
      deploymentPrimaryLocation: $(deploymentPrimaryLocation)
      deploymentSecondaryLocation: $(deploymentSecondaryLocation)
      deployApim: true
      eapimEnvironmentName: 'Test'
