name: $(BuildDefinitionName)_tag-$(BuildID)_at-$(Date:yyyyMMdd)$(Rev:.r)
resources:
  repositories:
    - repository: self
      persistCredentials: true
      clean: true
    - repository: devopsTemplates
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/operations-devops-pipeline-templates

trigger:
  branches:
    include:
    - master
    exclude:
    - develop/*

variables:
- name: applicationName
  value: ncsauth
- group: ncs-b2c-global


stages:

- stage: build
  displayName: Build
  jobs:
  - template: /Application/dotnet/jobs/build-application.yml@devopsTemplates
    parameters:
      applicationName: $(applicationName)
      webPublish: false


- stage: testTenantSetup
  displayName: Tenant Setup - TEST
  jobs:
  - template: yaml/jobs/tenant-setup.yml
    parameters:
      environmentName: test
      tenantId: $(testAzureB2cTenantId)
      uploaderPrincipalClientId: $(testAdoPrincipalClientId)
      uploaderPrincipalSecret: $(testAdoPrincipalSecret)
      proxyAppRegistrationClientId: $(testProxyIdentityFrameworkClientId)
      proxyAppRegistrationObjectId: $(testProxyIdentityFrameworkObjectId)
      eapimRootUrl: oat-api-customerengagement.platform.education.gov.uk

- stage: deployTest
  displayName: Deploy - TEST
  dependsOn: 
  - testTenantSetup
  jobs:
  - template: yaml/jobs/deploy.yml
    parameters:
      environmentName: 'test'
      environmentId: 't01'
      serviceConnection: $(testServiceConnection)
      subscriptionId: $(testSubscriptionId)
      deploymentPrimaryLocation: $(deploymentPrimaryLocation)
      deploymentSecondaryLocation: $(deploymentSecondaryLocation)
      deployApim: true
      eapimEnvironmentName: 'Test'

# - stage: postDeployTest
#   displayName: Post Deploy - TEST
#   dependsOn: deployTest
#   jobs:
#   - job: azCli
#     displayName: Add App Registrations
#     pool:
#       vmImage: ubuntu-latest
#     steps:
#     - template: yaml/steps/add-service-principals.yml
#       parameters:
#         serviceConnection: $(testServiceConnection)
#         environmentName: 'test'
#         identityFrameworkSecret: $(testIdentPrincipalSecret)
#         proxyIdentityFrameworkSecret: $(testIdentProxyPrincipalSecret)
#         graphAccessSecret: $(testGraphPrincipalSecret)