resources:
  repositories:
    - repository: devopsTemplates
      type: github
      endpoint: DfE Digital
      name: DFE-Digital/operations-devops-pipeline-templates

trigger:
  branches:
    include:
    - master
    exclude:
    - develop/*

variables:
  armOutputsName: b2cOutputs
  applicationName: ncsauth
  environmentName: dev

stages:
- stage: buildAndDeploy
  jobs:
  - job: armDeploy
    pool:
      vmImage: ubuntu-latest
    steps:
      - checkout: self
      - download: none
      - task: AzureResourceManagerTemplateDeployment@3
        displayName: Create Infrastructure
        inputs:
          deploymentScope: 'Resource Group'
          azureResourceManagerConnection: $(serviceConnection)
          subscriptionId: $(subscriptionId)
          resourceGroupName: $(resourceGroupName)
          location: $(deploymentLocation)
          csmFile: '$(Build.SourcesDirectory)/arm/template.json'
          overrideParameters: '-applicationName "ncsauth"
            -environmentName "$(environmentName)"
            -publisherEmail "test@test.com"
            -publisherName "deploymentTest"
            -apimSku "Developer"
            -apimSkuCount "1"
            -servicePlanSkuName "B1"
            -servicePlanSkuTier "Basic"
            -servicePlanSkuCount "1"
            -secondaryStorageLocation "northeurope"
            -alertWebHookUrl "http://www.test.com"'
          deploymentMode: 'Incremental'  
          deploymentOutputs: $(armOutputsName) 
          
      - task: AzureAppServiceManage@0
        displayName: Install Site Extensions
        inputs:
          azureSubscription: $(serviceConnection)
          Action: 'Install Extensions'
          WebAppName: $(applicationName)-$(environmentName)-function
          ExtensionsList: 'Microsoft.VisualStudio.SnapshotDebugger.AzureAppServices.Standalone'
                  
      
