parameters:
- name: serviceConnection
  type: string
- name: subscriptionId
  type: string
- name: applicationName
  type: string
- name: environmentName
  type: string
- name: location
  type: string
- name: overrideParameters
  type: string
- name: resourceGroupName
  type: string

steps:
- template: /Infrastructure/steps/deploy-template.yml@devopsTemplates
  parameters:
    serviceConnection: ${{parameters.serviceConnection}}
    subscriptionId: ${{parameters.subscriptionId}}
    resourceGroupName: ${{parameters.resourceGroupName}}
    location: ${{parameters.location}}
    templateFilePath: '$(Build.SourcesDirectory)/arm/template.json'
    armParameterOverrideString: ${{parameters.overrideParameters}}
- task: AzureAppServiceManage@0
  displayName: Install Site Extensions
  inputs:
    azureSubscription: ${{parameters.serviceConnection}}
    Action: 'Install Extensions'
    WebAppName: ${{parameters.applicationName}}-${{parameters.environmentName}}-function
    ExtensionsList: 'Microsoft.VisualStudio.SnapshotDebugger.AzureAppServices.Standalone'
- template: /Application/dotnet/steps/deploy-function.yml@templates
  parameters:
    azureSubscription: ${{parameters.serviceConnection}}
    applicationName: ${{parameters.applicationName}}
    environmentName: ${{parameters.environmentName}}