resources:
  repositories:
    - repository: devopsTemplates
      type: github
      endpoint: DfE Signin
      name: DFE-Digital/operations-devops-pipeline-templates

trigger:
  branches:
    include:
    - master
    - feature/*
    exclude:
    - develop/*


variables:
s  applicationName: ncsauth

stages:
- stage: Build
  jobs:
  - template: /Application/dotnet/jobs/build-application.yml@devopsTemplates
    parameters:
      applicationName: $(applicationName)
      webPublish: false

- stage: Deploy
  jobs:
  - template: /Application/dotnet/jobs/deploy-function.yml@devopsTemplates
    parameters:
      applicationName: $(applicationName)
      environmentName: dev
      serviceConnection: $(serviceConnection)
      subscriptionId: $(subscriptionId)
      resourceGroupName: $(resourceGroupName)
      location: $(deploymentLocation)
      templatePath: '$(Build.SourcesDirectory)/arm/template.json'
      overrideParameters: '-applicationName "ncsauth"
        -environmentName "dev"
        -publisherEmail "test@test.com"
        -publisherName "deploymentTest"
        -apimSku "Developer"
        -apimSkuCount "1"
        -servicePlanSkuName "B1"
        -servicePlanSkuTier "Basic"
        -servicePlanSkuCount "1"
        -secondaryStorageLocation "northeurope"
        -alertWebHookUrl "http://www.test.com"
        -B2CTenant ""
        -B2CSignUpPolicy ""
        -B2CSignupConfirmPolicy ""
        -B2CPasswordResetConfirmPolicy ""
        -B2CClientId ""
        -B2CRedirectUri ""
        -B2CAuthorizationUrl ""
        -ClientSigningKey ""
        -SMTPServer ""
        -SMTPUsername ""
        -SMTPPassword ""
        -SMTPUseSSL true
        -SMTPFromAddress ""
        -SMTPSubject ""
        -SignupEmailSubject ""
        -SignupConfirmationEmailSubject ""
        -PasswordResetConfirmationEmailSubject ""'