name: $(BuildDefinitionName)_tag-$(BuildID)_at-$(Date:yyyyMMdd)$(Rev:.r)
resources:
  repositories:
    - repository: self
      persistCredentials: true
      clean: true
    - repository: devopsTemplates
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/operations-devops-pipeline-templates


variables:
- name: applicationName
  value: authncs
- name: parsedTestExtensionAppId
  value: $[ replace(variables['testProxyIdentityAppClientId'],'-','') ]
- name: parsedDevExtensionAppId
  value: $[ replace(variables['devProxyIdentityAppClientId'],'-','') ]
- group: ncs-b2c-global

stages:

- stage: build
  displayName: Build
  jobs:
  - template: /Application/dotnet/jobs/build-application.yml@devopsTemplates
    parameters:
      applicationName: $(applicationName)
      webPublish: false
      nugetConfigPath: nuget.config

- stage: devTenantSetup
  displayName: Tenant Setup - DEV
  dependsOn:
    - build
  jobs:
  - template: yaml/jobs/tenant-setup.yml
    parameters:
      variableGroupName: ncs-b2c-dev
      applicationName: $(applicationName)
      environmentName: dev
      tenantId: $(devAzureB2cTenantId)
      uploaderPrincipalClientId: $(devPipelineManagementClientId)
      uploaderPrincipalClientSecret: $(devPipelineManagementClientSecret)
      proxyAppRegistrationClientId: $(devProxyIdentityAppClientId)
      proxyAppRegistrationObjectId: $(devProxyIdentityAppObjectId)
      identAppRegistrationClientId: $(devIdentityAppClientId)
      signinRedirectRoot: s141d01-signin-int.azurewebsites.net
      eapimRootUrl: dev-api-customerengagement.platform.education.gov.uk

- stage: deployDev
  displayName: Deploy - DEV
  dependsOn:
  - build
  - devTenantSetup
  jobs:
  - template: yaml/jobs/deploy.yml
    parameters:
      variableGroupName: ncs-b2c-dev
      applicationName: $(applicationName)
      environmentName: 'dev'
      functionServicePlanSkuName: $(functionServicePlanSkuName)
      functionServicePlanSkuTier: $(functionServicePlanSkuTier)
      functionServicePlanSkuCount: $(functionServicePlanSkuCount)
      b2cSignUpPolicy: $(b2cSignUpPolicy)
      b2cSignupConfirmPolicy: $(b2cSignupConfirmPolicy)
      b2cPasswordResetConfirmPoicy: $(b2cPasswordResetConfirmPoicy)
      b2cChangeEmailPolicy: $(b2cChangeEmailPolicy)
      b2cAuthorizationUrl: $(b2cAuthorizationUrl)
      ncsApimSubscriptionKey: $(ncsApimSubscriptionKey)
      ncsDssApiRoot: $(devNcsDssApiRoot)
      ncsDssApiKey: $(ncsDevDssApiKey)
      ncsDssSearchApiVersion: $(ncsDssSearchApiVersion)
      ncsDssSearchApiUrlRoute: $(ncsDssSearchApiUrlRoute)
      ncsDssCreateCustomerApiUrlRoute: $(ncsDssCreateCustomerApiUrlRoute)
      ncsDssCreateContactApiUrlRoute: $(ncsDssCreateContactApiUrlRoute)
      ncsDssCreateIdentityApiUrlRoute: $(ncsDssCreateIdentityApiUrlRoute)
      ncsDssGetCustomerUrlRoute: $(ncsDssGetCustomerUrlRoute)
      ncsDigitalIdentityRoute: $(ncsDigitalIdentityRoute)
      environmentId: 'd01'
      serviceConnection: $(devServiceConnection)
      subscriptionId: $(devSubscriptionId)
      relyingPartyAppClientId: $(devRelyAppClientId)
      clientSigningKey: $(devClientSigningKey)
      graphAccessClientId: $(devGraphAccessClientId)
      graphAccessClientSecret: $(devGraphAccessClientSecret)
      deploymentPrimaryLocation: $(deploymentPrimaryLocation)
      policyCertThumbprint: $(devB2cApimCertThumbprint)
      extensionAppId: $(parsedDevExtensionAppId)
      notifyAidedSignupEmailTemplateId: $(devNotifyAidedSignupEmailTemplateId)
      notifySelfSignupEmailTemplateId: $(devNotifySelfSignupEmailTemplateId)
      notifyPasswordResetConfirmationEmailTemplateId: $(devNotifyPasswordResetConfirmationEmailTemplateId)
      notifyEmailChangeConfirmationEmailNewEmailTemplateId: $(devNotifyEmailChangeConfirmationEmailNewEmailTemplateId)
      notifyEmailChangeConfirmationEmailOldEmailTemplateId: $(devNotifyEmailChangeConfirmationEmailOldEmailTemplateId)
      eapimServiceConnection: $(eapimServiceConnection)
      eapimEnvironmentName: 'Development'
      eapimResourceGroupName: c106d01-eapim-custeng
      eapimServiceName: c106d01-apim-custeng