name: $(BuildDefinitionName)_tag-$(BuildID)_at-$(Date:yyyyMMdd)$(Rev:.r)
resources:
  repositories:
    - repository: self
      persistCredentials: true
      clean: true
    - repository: devopsTemplates
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/operations-devops-pipeline-templates

trigger:
  branches:
    include:
    - master
    - develop

variables:
- name: applicationName
  value: authncs
- group: ncs-b2c-global

stages:

- stage: preDeploy
  displayName: Pre Deploy
  jobs:
  - job: tokeniseNamedValues
    displayName: Tokenise Eapim tokeniseNamedValues
    pool:
      vmImage: ubuntu-latest
    variables:
      dsiB2cDevCertThumbprint: DEVCERTTHUMBPRINT
      dsiB2cDevFuncionKey: DEVFUNCTIONKEY
      dsiB2cTestCertThumbprint: TESTCERTTHUMBPRINT
      dsiB2cTestFuncionKey: TESTFUNCTIONKEY
    steps:
    - task: Tokenization@2
      displayName: Tokenise CSV Files
      inputs:
        SourcePath: '$(Build.SourcesDirectory)/eapim/namedValues'
        TargetFileNames: '*.csv'
        RequireVariable: true
        TokenStart: '{{'
        TokenEnd: '}}'

- stage: build
  displayName: Build
  jobs:
  - template: /Application/dotnet/jobs/build-application.yml@devopsTemplates
    parameters:
      applicationName: $(applicationName)
      webPublish: false

- stage: testTenantSetup
  displayName: Tenant Setup - TEST
  jobs:
  - template: yaml/jobs/tenant-setup.yml
    parameters:
      applicationName: $(applicationName)
      environmentName: test
      tenantId: $(testAzureB2cTenantId)
      uploaderPrincipalClientId: $(testPipelineMangementClientId)
      uploaderPrincipalClientSecret: $(testPipelineManagementClientSecret)
      proxyAppRegistrationClientId: $(testProxyIdentityAppClientId)
      proxyAppRegistrationObjectId: $(testProxyIdentityAppObjectId)
      identAppRegistrationClientId: $(testIdentityAppClientId)
      signinRedirectRoot: test-interactions.signin.education.gov.uk
      eapimRootUrl: test-api-customerengagement.platform.education.gov.uk

- stage: deployTest
  displayName: Deploy - TEST
  dependsOn:
  - build
  - testTenantSetup
  jobs:
  - template: yaml/jobs/deploy.yml
    parameters:
      applicationName: $(applicationName)
      environmentName: 'test'
      environmentId: 't01'
      serviceConnection: $(testServiceConnection)
      subscriptionId: $(testSubscriptionId)
      clientId: $(testAzureB2cTenantId)
      clientSigningKey: $(testClientSigningKey)
      graphAccessClientId: $(testGraphAccessClientId)
      graphAccessClientSecret: $(testGraphAccessClientSecret)
      deploymentPrimaryLocation: $(deploymentPrimaryLocation)
      deploymentSecondaryLocation: $(deploymentSecondaryLocation)
      deployApim: true
      eapimEnvironmentName: 'Test'
      eapimNamedValuesFileName: '$(Build.SourcesDirectory)/eapim/namedvalues/valuesTest.csv'

# - stage: deployDev
#   displayName: Deploy - DEV
#   jobs:
#   - template: yaml/jobs/deploy.yml
#     parameters:
#       environmentName: 'test'
#       environmentId: 'd01'
#       serviceConnection: $(devServiceConnection)
#       subscriptionId: $(devSubscriptionId)
#       clientId: $(devAzureB2cTenantId)
#       clientSigningKey: $(devClientSigningKey)
#       graphAccessClientId: $(devGraphAccessClientId)
#       graphAccessClientSecret: $(devGraphAccessClientSecret)
#       deploymentPrimaryLocation: $(deploymentPrimaryLocation)
#       deploymentSecondaryLocation: $(deploymentSecondaryLocation)
#       deployApim: true
#       eapimEnvironmentName: 'Test'


