  trigger:
  branches:
    include:
    - master
    exclude:
    - develop/*

variables:
  armOutputsName: b2cOutputs

stages:
- stage: buildAndDeploy
  jobs:
  - job: armDeploy
    pool:
      vmImage: windows-latest
    steps:
      - checkout: self
      - download: none
      - task: AzureResourceManagerTemplateDeployment@3
        displayName: Create Infrastructure
        inputs:
          deploymentScope: 'Resource Group'
          azureResourceManagerConnection: $(serviceConnection)
          subscriptionId: $(subscriptionId)
          resourceGroupName: $(resourceGroupName)
          location: $(deploymentLocation)
          csmFile: '$(Build.SourcesDirectory)/arm/template.json'
          overrideParameters: '-applicationName "ncsauth"
            -environmentName "dev"
            -publisherEmail "test@test.com"
            -publisherName "deploymentTest"
            -apimSku "Developer"
            -apimSkuCount "1"
            -servicePlanSkuName "B1"
            -servicePlanSkuTier "Basic"
            -servicePlanSkuCount "1"
            -secondaryStorageLocation "northeurope"
            -alertWebHookUrl "http://www.test.com"'
          deploymentMode: 'Incremental'  
          deploymentOutputs: $(armOutputsName) 
          
      - task: ARMTemplateOutputs@0
        inputs:
          ARMOutputs: $(armOutputsName) 

      - task: AzureAppServiceManage@0
        inputs:
          azureSubscription: $(serviceConnection)
          Action: 'Install Extensions'
          WebAppName: 'ncsauth-dev-function'
          ExtensionsList: 'Microsoft.VisualStudio.SnapshotDebugger.AzureAppServices.Standalone'
                  
      
