name: $(BuildDefinitionName)_tag-$(BuildID)_at-$(Date:yyyyMMdd)$(Rev:.r)
resources:
  repositories:
  # Defult branch is master
    - repository: devopsTemplates
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/login.dfe.devops
      ref: feature/DSI-5680

variables:
- group: ncs-b2c-global
- group: ncs-b2c-dev

stages:


    
# Code scaning tools
- stage: RevertSlot
  displayName: Load Secrets in KeyVault 
  jobs:
  - job: waitForValidation
    timeoutInMinutes: 2
    pool: server
    steps: 
    - task: ManualIntervention@8
      inputs:
        instructions: 'if back roll needed'
  
- stage: Revert slot
  displayName: swap back
  dependsOn: RevertSlot
  jobs:
  - job: test
    steps: 
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          
          echo 'Hello world'
