parameters:
- name: environmentName
  type: string
- name: environmentId
  type: string
- name: serviceConnection
  type: string
- name: subscriptionId
  type: string
- name: clientId
  type: string
- name: graphAccessClientId
  type: string
- name: graphAccessClientSecret
  type: string
- name: deploymentPrimaryLocation
  type: string
- name: deploymentSecondaryLocation
  type: string
- name: deployApim
  type: boolean
  default: false
- name: eapimEnvironmentName
  type: string
  values:
  - Development
  - Test
  - Oat
  - Production

jobs:
- template: /Application/dotnet/jobs/deploy-function.yml@devopsTemplates
  parameters:
      applicationName: $(applicationName)
      environmentName: ${{parameters.environmentName}}
      serviceConnection: ${{parameters.serviceConnection}}
      subscriptionId: ${{parameters.subscriptionId}}
      resourceGroupName: s141${{parameters.environmentId}}-$(applicationName)
      location: ${{parameters.deploymentPrimaryLocation}}
      templatePath: '$(Build.SourcesDirectory)/arm/template.json'
      overrideParameters: '
      -applicationName "$(applicationName)"
      -environmentName "${{parameters.environmentName}}"
      -servicePlanSkuName "$(functionServicePlanSkuName)"
      -servicePlanSkuTier "$(functionServicePlanSkuTier)"
      -servicePlanSkuCount "$(functionServicePlanSkuCount)"
      -secondaryStorageLocation "${{parameters.deploymentSecondaryLocation}}"
      -alertWebHookUrl "http://www.test.com"
      -B2CTenant "${{parameters.environmentName}}authncs.onmicrosoft.com"
      -B2CSignUpPolicy "$(b2cSignUpPolicy)"
      -B2CSignupConfirmPolicy "$(b2cSignupConfirmPolicy)"
      -B2CPasswordResetConfirmPolicy "$(b2cPasswordResetConfirmPoicy)"
      -B2CClientId "${{parameters.clientId}}"
      -B2CRedirectUri "https://jwt.ms"
      -B2CAuthorizationUrl "$(b2cAuthorizationUrl)"
      -ClientSigningKey "$(clientSigningKey)"
      -SMTPServer "$(smtpServer)"
      -SMTPUsername "$(smtpUsername)"
      -SMTPPassword "$(smtpPassword)"
      -SMTPFromAddress "$(smtpFromAddress)"
      -SMTPSubject "Sign-in to NCS"
      -SignupEmailSubject "Create your account"
      -SignupConfirmationEmailSubject "Verify your account"
      -PasswordResetConfirmationEmailSubject "Verify your account"
      -AccountActivationEmailExpiryInSeconds "86400"
      -NCSApimSubscriptionKey "$(ncsApimSubscriptionKey)"
      -NCSDSSApiKey "$(ncsDssApiKey)"
      -NCSDSSSearchApiUrl "$(ncsDssSearchApiUrl)"
      -NCSDSSSearchApiVersion "$(ncsDssSearchApiVersion)"
      -NCSDSSCreateCustomerApiUrl "$(ncsDssCreateCustomerApiUrl)"
      -NCSDSSCreateContactApiUrl "$(ncsDssCreateContactApiUrl)"
      -NCSDSSCreateIdentityApiUrl "$(NCSDSSCreateIdentityApiUrl)"
      -TouchpointId "1000000000"'
      eapimRegister: ${{parameters.deployApim}}
      eapimServiceConnection: $(eapimServiceConnection)
      eapimEnvironment: ${{parameters.eapimEnvironmentName}}
      eapimProductName: 'NCS Identity'
      eapimProductContactEmail: paul.sheridan@digital.education.gov.uk
      eapimApiPublishedName: 'NCS Identity'
      eapimApiOpenApiSchemaPath: '/api/swagger'
      eapimApiPublishedPath: ncsauth
      eapimApiXmlPolicyPath: '$(Build.SourcesDirectory)/eapim/api/policy.xml'