parameters:
- name: applicationName
  type: string
- name: environmentName
  type: string
- name: environmentId
  type: string
- name: serviceConnection
  type: string
- name: eapimServiceConnection
  type: string
- name: subscriptionId
  type: string
- name: clientId
  type: string
- name: clientSigningKey
  type: string
- name: graphAccessClientId
  type: string
- name: graphAccessClientSecret
  type: string
- name: extensionAppId
  type: string
  default: '9509a3af9e674a7d9443a094c02c8e69'
- name: deploymentPrimaryLocation
  type: string
- name: deploymentSecondaryLocation
  type: string
- name: policyCertThumbprint
  type: string
  default: 'EC634E6E424711C4060CA3821C3A4F457BC6D244'
- name: eapimEnvironmentName
  type: string
  values:
  - Development
  - Test
  - Oat
  - Production

jobs:
- deployment: Deploy
  displayName: Deploy Azure Function
  environment: ${{parameters.environmentName}}
  pool:
    vmImage: windows-latest
  variables:
    dsiB2cCertThumbprint: ${{parameters.policyCertThumbprint}}
    overrideParameters: '
      -applicationName "$(applicationName)"
      -environmentName "${{parameters.environmentName}}"
      -servicePlanSkuName "$(functionServicePlanSkuName)"
      -servicePlanSkuTier "$(functionServicePlanSkuTier)"
      -servicePlanSkuCount "$(functionServicePlanSkuCount)"
      -secondaryStorageLocation "${{parameters.deploymentSecondaryLocation}}"
      -alertWebHookUrl "http://www.test.com"
      -B2CTenantShortName "${{parameters.environmentName}}authncs"
      -B2CTenantFullName "${{parameters.environmentName}}authncs.onmicrosoft.com"
      -B2CSignUpPolicy "$(b2cSignUpPolicy)"
      -B2CSignupConfirmPolicy "$(b2cSignupConfirmPolicy)"
      -B2CPasswordResetConfirmPolicy "$(b2cPasswordResetConfirmPoicy)"
      -B2CClientId "${{parameters.clientId}}"
      -B2CRedirectUri "https://jwt.ms"
      -B2CAuthorizationUrl "$(b2cAuthorizationUrl)"
      -ClientSigningKey "${{parameters.clientSigningKey}}"
      -SMTPServer "$(smtpServer)"
      -SMTPUsername "$(smtpUsername)"
      -SMTPPassword "$(smtpPassword)"
      -SMTPFromAddress "$(smtpFromAddress)"
      -SMTPSubject "Sign-in to NCS"
      -SignupEmailSubject "Create your account"
      -SignupConfirmationEmailSubject "Verify your account"
      -PasswordResetConfirmationEmailSubject "Verify your account"
      -AccountActivationEmailExpiryInSeconds "86400"
      -NCSApimSubscriptionKey "$(ncsApimSubscriptionKey)"
      -NCSDSSApiKey "$(ncsDssApiKey)"
      -NCSDSSSearchApiUrl "$(ncsDssSearchApiUrl)"
      -NCSDSSSearchApiVersion "$(ncsDssSearchApiVersion)"
      -NCSDSSCreateCustomerApiUrl "https://at.api.nationalcareersservice.org.uk/customers/api/Customers/"
      -NCSDSSCreateContactApiUrl "https://at.api.nationalcareersservice.org.uk/contactdetails/api/customers/{0}/ContactDetails/"
      -NCSDSSCreateIdentityApiUrl "https://at.api.nationalcareersservice.org.uk/digitalidentities/api/identity"
      -TouchpointId "1000000000"
      -B2CGraphAccessClientId "${{parameters.graphAccessClientId}}"
      -B2CGraphAccessClientSecret "${{parameters.graphAccessClientSecret}}"
      -EmailChangeConfirmationEmailSubjectNewEmail "Email change request"
      -EmailChangeConfirmationEmailSubjectOldEmail "Email change request"
      -B2CChangeEmailPolicy "B2C_1A_changeemail"
      -ExtensionAppId "${{parameters.extensionAppId}}"'

  strategy:
    runOnce:
      deploy:
        steps:
        - template: /Infrastructure/steps/deploy-template.yml@devopsTemplates
          parameters:
            serviceConnection: ${{parameters.serviceConnection}}
            subscriptionId: ${{parameters.subscriptionId}}
            resourceGroupName: s141${{parameters.environmentId}}-${{parameters.environmentName}}${{parameters.applicationName}}
            location: ${{parameters.deploymentPrimaryLocation}}
            templateFilePath: '$(Build.SourcesDirectory)/arm/template.json'
            armParameterOverrideString: $(overrideParameters)

        - pwsh: |
            Write-Host "##vso[task.setvariable variable=dsiB2cCertThumbprint]XXXXXX"
            Write-Host "##vso[task.setvariable variable=dsiB2cFunctionKey]$($env:ARMOUTPUT_FUNCTIONDEFAULTKEY)"
          env:
          displayName: Set Named values

        - task: Tokenization@2
          displayName: Tokenise CSV Files
          inputs:
            SourcePath: '$(Build.SourcesDirectory)\eapim\namedValues'
            TargetFileNames: '*.csv'
            RequireVariable: true
            TokenStart: '{{'
            TokenEnd: '}}'

        - task: AzureAppServiceManage@0
          displayName: Install Site Extensions
          inputs:
            azureSubscription: ${{parameters.serviceConnection}}
            Action: 'Install Extensions'
            WebAppName: ${{parameters.applicationName}}-${{parameters.environmentName}}-function
            ExtensionsList: 'Microsoft.VisualStudio.SnapshotDebugger.AzureAppServices.Standalone'

        - template: /Application/dotnet/steps/deploy-function.yml@devopsTemplates
          parameters:
            azureSubscription: ${{parameters.serviceConnection}}
            applicationName: ${{parameters.applicationName}}
            environmentName: ${{parameters.environmentName}}

        - pwsh : |
            $url = "$($env:ARMOUTPUT_FUNCTIONURL)/swagger"
            $filePath = "$($env:BUILD_SOURCESDIRECTORY)\definition.json"
            Write-Host "url: $($url)"
            Write-Host "filePath: $($filePath)"
            Invoke-RestMethod -Method Get -Uri $url -ContentType "application/json" -OutFile $filePath -MaximumRetryCount 5 -RetryIntervalSec 10
          name: getDefinition
          displayName: Download OpenApi Definition

        - template: /Application/dotnet/steps/import-function-eapim.yml@devopsTemplates
          parameters:
            serviceConnection: ${{parameters.serviceConnection}}
            eapimServiceConnection: ${{parameters.eapimServiceConnection}}
            functionName: $(armOutput.functionName)
            functionKey: $(armOutput.functionMasterKey)
            functionUrl: $(armOutput.functionUrl)
            productName: 'NCS Identity'
            publishContactEmail: 'paul.sheridan@digital.education.gov.uk'
            publishApiName: 'NCS Identity'
            publishApiOpenApiSchemaPath: '$(Build.SourcesDirectory)\definition.json'
            publishApiPath: ncsauth
            publishApiXmlPolicyPath: '$(Build.SourcesDirectory)\eapim\api\policy.xml'
            eapimEnvironment: ${{parameters.eapimEnvironmentName}}
            namedValuesIncluded: true
            namedValuesFileName: '$(Build.SourcesDirectory)\eapim\namedValues\values.csv'