parameters:
- name: environmentName
  type: string
- name: environmentId
  type: string
- name: serviceConnection
  type: string
- name: subscriptionId
  type: string
- name: deploymentPrimaryLocation
  type: string
- name: deploymentSecondaryLocation
  type: string
- name: deployApim
  type: boolean
  default: false

jobs:
- template: /Application/dotnet/jobs/deploy-function.yml@devopsTemplates
  parameters:
      applicationName: $(applicationName)
      environmentName: ${{parameters.environmentName}}
      serviceConnection: ${{parameters.serviceConnection}}
      subscriptionId: ${{parameters.subscriptionId}}
      resourceGroupName: s141${{parameters.environmentId}}-$(applicationName)
      location: ${{parameters.deploymentPrimaryLocation}}
      templatePath: '$(Build.SourcesDirectory)/arm/template.json'
      overrideParameters: '
      -applicationName "$(applicationName)"
      -environmentName "${{parameters.environmentName}}"
      -publisherEmail "test@test.com"
      -publisherName "deploymentTest"
      -servicePlanSkuName "B1"
      -servicePlanSkuTier "Basic"
      -servicePlanSkuCount "1"
      -secondaryStorageLocation "${{parameters.deploymentSecondaryLocation}}"
      -alertWebHookUrl "http://www.test.com"
      -B2CTenant "B2Cdemotenant"
      -B2CSignUpPolicy "B2C_1A_signup_invitation"
      -B2CSignupConfirmPolicy "B2C_1A_signup_confirmation"
      -B2CPasswordResetConfirmPolicy "B2C_1A_passwordResetConformation"
      -B2CClientId "$(b2cClientId)"
      -B2CRedirectUri "https://jwt.ms"
      -B2CAuthorizationUrl "https://{0}.b2clogin.com/{0}.onmicrosoft.com/{1}/oauth2/v2.0/authorize?client_id={2}&nonce={4}&redirect_uri={3}&scope=openid&response_type=id_token"
      -ClientSigningKey "$(clientSigningKey)"
      -SMTPServer "$(smtpServer)"
      -SMTPUsername "$(smtpUsername)"
      -SMTPPassword "$(smtpPassword)"
      -SMTPFromAddress "$(smtpFromAddress)"
      -SMTPSubject "Sign-in to NCS"
      -SignupEmailSubject "Create your account"
      -SignupConfirmationEmailSubject "Verify your account"
      -PasswordResetConfirmationEmailSubject "Verify your account"
      -AccountActivationEmailExpiryInSeconds "86400"
      -NCSApimSubscriptionKey "$(ncsApimSubscriptionKey)"
      -NCSDSSApiKey "$(ncsDssApiKey)"
      -NCSDSSSearchApiUrl "$(ncsDssSearchApiUrl)"
      -NCSDSSSearchApiVersion "$(ncsDssSearchApiVersion)"
      -NCSDSSCreateCustomerApiUrl "https://at.api.nationalcareersservice.org.uk/customers/api/Customers/"
      -NCSDSSCreateContactApiUrl "https://at.api.nationalcareersservice.org.uk/contactdetails/api/customers/{0}/ContactDetails/"
      -NCSDSSCreateIdentityApiUrl "https://at.api.nationalcareersservice.org.uk/digitalidentities/api/identity"
      -TouchpointId "1000000000"
      -B2CTenantId "devauthncs.onmicrosoft.com"
      -B2CGraphAccessClientId "9e28727a-9abe-4d3b-80e8-367889846e1c"
      -B2CGraphAccessClientSecret "S5EUqH6PyEI.2qqztYlC4Pqx.1B.~8GTe7"
      -EmailChangeConfirmationEmailSubjectNewEmail "Activate your new email address"
      -EmailChangeConfirmationEmailSubjectOldEmail "Changed email address"
      -B2CChangeEmailPolicy "B2C_1A_changeemail"
      -ExtensionAppId "9509a3af9e674a7d9443a094c02c8e69"'
      eapimRegister: ${{parameters.deployApim}}
      eapimServiceConnection: $(eapimServiceConnection)
      eapimProductName: 'NCS Identity'
      eapimProductContactEmail: paul.sheridan@digital.education.gov.uk
      eapimApiPublishedName: 'NCS Identity'
      eapimApiOpenApiSchemaPath: '/api/swagger'
      eapimApiPublishedPath: ncsauth
      eapimApiXmlPolicyPath: '$(Build.SourcesDirectory)/eapim/api/policy.xml'