parameters:
- name: environmentName
  type: string
- name: tenantId
  type: string
- name: uploaderPrincipalClientId
  type: string
- name: uploaderPrincipalSecret
  type: string
- name: proxyAppRegistrationClientId
  type: string
- name: proxyAppRegistrationObjectId
  type: string
- name: eapimRootUrl
  
jobs:
- job: tenantSetup
  displayName: B2C Tenant Setup 
  pool:
    vmImage: windows-latest
  steps:
    - task: Tokenization@2
      displayName: Tokenise Policy Files
      inputs:
        SourcePath: '$(Build.SourcesDirectory)\policy\'
        TargetFileNames: '*.xml'
        RequireVariable: true
        TokenStart: '__'
        TokenEnd: '__'
    - pwsh: 
        Write-Host "(uc) environmentName" $Env:ENVIRONMENTNAME 
        Write-Host "(lc) environmentName" $Env:environmentName 
      env:
        environmentName: ${{parameters.environmentName}}
        tenantId: ${{parameters.tenantId}}
        uploaderPrincipalClientId: ${{parameters.uploaderPrincipalClientId}}
        uploaderPrincipalSecret:  ${{parameters.uploaderPrincipalSecret}}
        policyDeployScriptUrl: 'https://raw.githubusercontent.com/DFE-Digital/operations-devops-tools/master/Powershell/B2C/deployPolicy.ps1'
        proxyAppRegistrationClientId: ${{parameters.proxyAppRegistrationClientId}}
        proxyAppRegistrationObjectId: ${{parameters.proxyAppRegistrationObjectId}}
        eapimRootUrl: ${{parameters.eapimRootUrl}}

    # - task: PowerShell@2
    #   inputs:
    #     filePath: '$(Build.SourcesDirectory)\scripts\UploadFrameworkPolicy.ps1'
    #     arguments: '-clientId ${{parameters.uploaderPrincipalClientId}} -clientSecret ${{parameters.uploaderPrincipalSecret}} -tenantId ${{parameters.tenantId}} -policyId B2C_1A_TrustFrameworkBase_invitation -pathToFile $(Build.SourcesDirectory)\policy\TrustFrameworkBase.xml'
    #     displayName: Policy Upload