parameters:
- name: environmentName
  type: string
- name: tenantId
  type: string
- name: uploaderPrincipalClientId
  type: string
- name: uploaderPrincipalClientSecret
  type: string
- name: proxyAppRegistrationClientId
  type: string
- name: proxyAppRegistrationObjectId
  type: string
- name: identAppRegistrationClientId
  type: string
- name: signinRedirectRoot
  type: string
- name: eapimRootUrl
  type: string
  
jobs:
- job: tenantSetup
  displayName: B2C Tenant Setup 
  pool:
    vmImage: windows-latest
  variables:
    #Uploader identity
    #interpolation - these are used by the interpolation step to customise the policies per environment
    environmentName: ${{parameters.environmentName}}
    proxyIdentAppRegistrationClientId: ${{parameters.proxyAppRegistrationClientId}}
    proxyIdentAppRegistrationObjectId: ${{parameters.proxyAppRegistrationObjectId}}
    identAppRegistrationClientId: ${{parameters.identAppRegistrationClientId}}
    signinRedirectRoot: ${{parameters.signinRedirectRoot}}
    eapimRootUrl: ${{parameters.eapimRootUrl}}
  steps:
    - task: Tokenization@2
      displayName: Tokenise Policy Files
      inputs:
        SourcePath: '$(Build.SourcesDirectory)\policy\'
        TargetFileNames: '*.xml'
        RequireVariable: true
        TokenStart: '__'
        TokenEnd: '__'
    - pwsh: |
        $scriptPath = "$($env:BUILD_SOURCESDIRECTORY)\scripts\UploadFrameworkPolicy.ps1"
        Write-Host Using Path : $scriptPath

        Write-Host UPLOADERPRINCIPALCLIENTID : $env:UPLOADERPRINCIPALCLIENTID
        Write-Host UPLOADER_PRINCIPAL_SECRET : $env:UPLOADER_PRINCIPAL_SECRET
        Write-Host TENANT_ID : $env:TENANT_ID

        $policyId = "B2C_1A_TrustFrameworkBase_Invitation"

        Write-Host EXAMPLE POLICY FILE PATH "$($env:BUILD_SOURCESDIRECTORY)\policy\TrustFrameworkBase_Invitation.xml"
        Write-Host EXAMPLE POLICY ID : $policyId

        # $policyId = "B2C_1A_TrustFrameworkBase_Invitation"
        # $policyFile = $env:BUILD_SOURCESDIRECTORY\policy\TrustFrameworkBase_Invitation.xml
        # Invoke-Expression "$scriptPath $env:UPLOADERPRINCIPALCLIENTID $env:UPLOADER_PRINCIPAL_SECRET $env:TENANT_ID $policyId $policyFile"

        # $policyId = "B2C_1A_TrustFrameworkExtensions_Invitation"
        # $policyFile = $env:BUILD_SOURCESDIRECTORY\policy\TrustFrameworkBase_Invitation.xml
        # Invoke-Expression "$scriptPath $env:UPLOADERPRINCIPALCLIENTID $env:UPLOADER_PRINCIPAL_SECRET $env:TENANT_ID $policyId $policyFile"

        # $policyId = "B2C_1A_Account_Signup"
        # $policyFile = $env:BUILD_SOURCESDIRECTORY\policy\Account_Signup.xml
        # Invoke-Expression "$scriptPath $env:UPLOADERPRINCIPALCLIENTID $env:UPLOADER_PRINCIPAL_SECRET $env:TENANT_ID $policyId $policyFile"

        # $policyId = "B2C_1A_Find_Email"
        # $policyFile = $env:BUILD_SOURCESDIRECTORY\policy\Find_Email.xml
        # Invoke-Expression "$scriptPath $env:UPLOADERPRINCIPALCLIENTID $env:UPLOADER_PRINCIPAL_SECRET $env:TENANT_ID $policyId $policyFile"

        # $policyId = "B2C_1A_Password_Reset_Conformation"
        # $policyFile = $env:BUILD_SOURCESDIRECTORY\policy\Password_Reset_Confirmation.xml
        # Invoke-Expression "$scriptPath $env:UPLOADERPRINCIPALCLIENTID $env:UPLOADER_PRINCIPAL_SECRET $env:TENANT_ID $policyId $policyFile"

        # $policyId = "B2C_1A_Password_Reset"
        # $policyFile = $env:BUILD_SOURCESDIRECTORY\policy\Password_Reset.xml
        # Invoke-Expression "$scriptPath $env:UPLOADERPRINCIPALCLIENTID $env:UPLOADER_PRINCIPAL_SECRET $env:TENANT_ID $policyId $policyFile"

        # $policyId = "B2C_1A_Signin_Invitation"
        # $policyFile = $env:BUILD_SOURCESDIRECTORY\policy\Signin_Invitation.xml
        # Invoke-Expression "$scriptPath $env:UPLOADERPRINCIPALCLIENTID $env:UPLOADER_PRINCIPAL_SECRET $env:TENANT_ID $policyId $policyFile"

        # $policyId = "B2C_1A_Signup_Confirmation"
        # $policyFile = $env:BUILD_SOURCESDIRECTORY\policy\Signup_Confirmation.xml
        # Invoke-Expression "$scriptPath $env:UPLOADERPRINCIPALCLIENTID $env:UPLOADER_PRINCIPAL_SECRET $env:TENANT_ID $policyId $policyFile"

        # $policyId = "B2C_1A_Signup_Invitation"
        # $policyFile = $env:BUILD_SOURCESDIRECTORY\policy\Signup_Invitation.xml
        # Invoke-Expression "$scriptPath $env:UPLOADERPRINCIPALCLIENTID $env:UPLOADER_PRINCIPAL_SECRET $env:TENANT_ID $policyId $policyFile"

        Write-Host 'Upload Complete'
      env:
        TENANT_ID: ${{parameters.tenantId}}
        UPLOADER_PRINCIPAL_SECRET: ${{parameters.uploaderPrincipalClientSecret}}
        UPLOADER_PRINCIPAL_CLIENTID : ${{parameters.uploaderPrincipalClientId}}
      displayName: Policy Upload

